# import xlrd
# from pprint import pprint

# def convertTo639():
# d = {}
# book = xlrd.open_workbook("list_of_iso_codes-934j.xls")
# sh = book.sheet_by_index(0)
# for i in range(1, sh.nrows):
# 	cell_value_class = sh.cell_value(rowx=i, colx=2)
# 	cell_value_id = sh.cell_value(rowx=i, colx=8)
# 	d[cell_value_class] = cell_value_id
#
# pprint(d)

str2iso_639_1 = {'Abkhaz': 'ab',
                 'Afar': 'aa',
                 'Afrikaans': 'af',
                 'Akan': 'ak',
                 'Albanian': 'sq',
                 'Amharic': 'am',
                 'Arabic': 'ar',
                 'Aragonese': 'an',
                 'Armenian': 'hy',
                 'Assamese': 'as',
                 'Avaric': 'av',
                 'Avestan': 'ae',
                 'Aymara': 'ay',
                 'Azerbaijani': 'az',
                 'Bambara': 'bm',
                 'Bashkir': 'ba',
                 'Basque': 'eu',
                 'Belarusian': 'be',
                 'Bengali; Bangla': 'bn',
                 'Bihari': 'bh',
                 'Bislama': 'bi',
                 'Bosnian': 'bs',
                 'Breton': 'br',
                 'Bulgarian': 'bg',
                 'Burmese': 'my',
                 'Catalan; Valencian': 'ca',
                 'Chamorro': 'ch',
                 'Chechen': 'ce',
                 'Chichewa; Chewa; Nyanja': 'ny',
                 'Chinese': 'zh',
                 'Chuvash': 'cv',
                 'Cornish': 'kw',
                 'Corsican': 'co',
                 'Cree': 'cr',
                 'Croatian': 'hr',
                 'Czech': 'cs',
                 'Danish': 'da',
                 'Divehi; Dhivehi; Maldivian;': 'dv',
                 'Dutch': 'nl',
                 'Dzongkha': 'dz',
                 'English': 'en',
                 'Esperanto': 'eo',
                 'Estonian': 'et',
                 'Ewe': 'ee',
                 'Faroese': 'fo',
                 'Fijian': 'fj',
                 'Finnish': 'fi',
                 'French': 'fr',
                 'Fula; Fulah; Pulaar; Pular': 'ff',
                 'Galician': 'gl',
                 'Ganda': 'lg',
                 'Georgian': 'ka',
                 'German': 'de',
                 'Greek, Modern': 'el',
                 'Guaraní': 'gn',
                 'Gujarati': 'gu',
                 'Haitian; Haitian Creole': 'ht',
                 'Hausa': 'ha',
                 'Hebrew (modern)': 'he',
                 'Herero': 'hz',
                 'Hindi': 'hi',
                 'Hiri Motu': 'ho',
                 'Hungarian': 'hu',
                 'Icelandic': 'is',
                 'Ido': 'io',
                 'Igbo': 'ig',
                 'Indonesian': 'id',
                 'Interlingua': 'ia',
                 'Interlingue': 'ie',
                 'Inuktitut': 'iu',
                 'Inupiaq': 'ik',
                 'Irish': 'ga',
                 'Italian': 'it',
                 'Japanese': 'ja',
                 'Javanese': 'jv',
                 'Kalaallisut, Greenlandic': 'kl',
                 'Kannada': 'kn',
                 'Kanuri': 'kr',
                 'Kashmiri': 'ks',
                 'Kazakh': 'kk',
                 'Khmer': 'km',
                 'Kikuyu, Gikuyu': 'ki',
                 'Kinyarwanda': 'rw',
                 'Kirundi': 'rn',
                 'Komi': 'kv',
                 'Kongo': 'kg',
                 'Korean': 'ko',
                 'Kurdish': 'ku',
                 'Kwanyama, Kuanyama': 'kj',
                 'Kyrgyz': 'ky',
                 'Lao': 'lo',
                 'Latin': 'la',
                 'Latvian': 'lv',
                 'Limburgish, Limburgan, Limburger': 'li',
                 'Lingala': 'ln',
                 'Lithuanian': 'lt',
                 'Luba-Katanga': 'lu',
                 'Luxembourgish, Letzeburgesch': 'lb',
                 'Macedonian': 'mk',
                 'Malagasy': 'mg',
                 'Malay': 'ms',
                 'Malayalam': 'ml',
                 'Maltese': 'mt',
                 'Manx': 'gv',
                 'Marathi (Marāṭhī)': 'mr',
                 'Marshallese': 'mh',
                 'Mongolian': 'mn',
                 'Māori': 'mi',
                 'Nauru': 'na',
                 'Navajo, Navaho': 'nv',
                 'Ndonga': 'ng',
                 'Nepali': 'ne',
                 'North Ndebele': 'nd',
                 'Northern Sami': 'se',
                 'Norwegian': 'no',
                 'Norwegian Bokmål': 'nb',
                 'Norwegian Nynorsk': 'nn',
                 'Nuosu': 'ii',
                 'Occitan': 'oc',
                 'Ojibwe, Ojibwa': 'oj',
                 'Old Church Slavonic, Church Slavonic, Old Bulgarian': 'cu',
                 'Oriya': 'or',
                 'Oromo': 'om',
                 'Ossetian, Ossetic': 'os',
                 'Panjabi, Punjabi': 'pa',
                 'Pashto, Pushto': 'ps',
                 'Persian (Farsi)': 'fa',
                 'Polish': 'pl',
                 'Portuguese': 'pt',
                 'Pāli': 'pi',
                 'Quechua': 'qu',
                 'Romanian': 'ro',
                 'Romansh': 'rm',
                 'Russian': 'ru',
                 'Samoan': 'sm',
                 'Sango': 'sg',
                 'Sanskrit (Saṁskṛta)': 'sa',
                 'Sardinian': 'sc',
                 'Scottish Gaelic; Gaelic': 'gd',
                 'Serbian': 'sr',
                 'Shona': 'sn',
                 'Sindhi': 'sd',
                 'Sinhala, Sinhalese': 'si',
                 'Slovak': 'sk',
                 'Slovene': 'sl',
                 'Somali': 'so',
                 'South Azerbaijani': 'az',
                 'South Ndebele': 'nr',
                 'Southern Sotho': 'st',
                 'Spanish; Castilian': 'es',
                 'Sundanese': 'su',
                 'Swahili': 'sw',
                 'Swati': 'ss',
                 'Swedish': 'sv',
                 'Tagalog': 'tl',
                 'Tahitian': 'ty',
                 'Tajik': 'tg',
                 'Tamil': 'ta',
                 'Tatar': 'tt',
                 'Telugu': 'te',
                 'Thai': 'th',
                 'Tibetan Standard, Tibetan, Central': 'bo',
                 'Tigrinya': 'ti',
                 'Tonga (Tonga Islands)': 'to',
                 'Tsonga': 'ts',
                 'Tswana': 'tn',
                 'Turkish': 'tr',
                 'Turkmen': 'tk',
                 'Twi': 'tw',
                 'Ukrainian': 'uk',
                 'Urdu': 'ur',
                 'Uyghur, Uighur': 'ug',
                 'Uzbek': 'uz',
                 'Venda': 've',
                 'Vietnamese': 'vi',
                 'Volapük': 'vo',
                 'Walloon': 'wa',
                 'Welsh': 'cy',
                 'Western Frisian': 'fy',
                 'Wolof': 'wo',
                 'Xhosa': 'xh',
                 'Yiddish': 'yi',
                 'Yoruba': 'yo',
                 'Zhuang, Chuang': 'za',
                 'Zulu': 'zu'}

str2iso_639_2T = {'Abkhaz': 'abk',
                  'Afar': 'aar',
                  'Afrikaans': 'afr',
                  'Akan': 'aka',
                  'Albanian': 'sqi',
                  'Amharic': 'amh',
                  'Arabic': 'ara',
                  'Aragonese': 'arg',
                  'Armenian': 'hye',
                  'Assamese': 'asm',
                  'Avaric': 'ava',
                  'Avestan': 'ave',
                  'Aymara': 'aym',
                  'Azerbaijani': 'aze',
                  'Bambara': 'bam',
                  'Bashkir': 'bak',
                  'Basque': 'eus',
                  'Belarusian': 'bel',
                  'Bengali; Bangla': 'ben',
                  'Bihari': 'bih',
                  'Bislama': 'bis',
                  'Bosnian': 'bos',
                  'Breton': 'bre',
                  'Bulgarian': 'bul',
                  'Burmese': 'mya',
                  'Catalan; Valencian': 'cat',
                  'Chamorro': 'cha',
                  'Chechen': 'che',
                  'Chichewa; Chewa; Nyanja': 'nya',
                  'Chinese': 'zho',
                  'Chuvash': 'chv',
                  'Cornish': 'cor',
                  'Corsican': 'cos',
                  'Cree': 'cre',
                  'Croatian': 'hrv',
                  'Czech': 'ces',
                  'Danish': 'dan',
                  'Divehi; Dhivehi; Maldivian;': 'div',
                  'Dutch': 'nld',
                  'Dzongkha': 'dzo',
                  'English': 'eng',
                  'Esperanto': 'epo',
                  'Estonian': 'est',
                  'Ewe': 'ewe',
                  'Faroese': 'fao',
                  'Fijian': 'fij',
                  'Finnish': 'fin',
                  'French': 'fra',
                  'Fula; Fulah; Pulaar; Pular': 'ful',
                  'Galician': 'glg',
                  'Ganda': 'lug',
                  'Georgian': 'kat',
                  'German': 'deu',
                  'Greek, Modern': 'ell',
                  'Guaraní': 'grn',
                  'Gujarati': 'guj',
                  'Haitian; Haitian Creole': 'hat',
                  'Hausa': 'hau',
                  'Hebrew (modern)': 'heb',
                  'Herero': 'her',
                  'Hindi': 'hin',
                  'Hiri Motu': 'hmo',
                  'Hungarian': 'hun',
                  'Icelandic': 'isl',
                  'Ido': 'ido',
                  'Igbo': 'ibo',
                  'Indonesian': 'ind',
                  'Interlingua': 'ina',
                  'Interlingue': 'ile',
                  'Inuktitut': 'iku',
                  'Inupiaq': 'ipk',
                  'Irish': 'gle',
                  'Italian': 'ita',
                  'Japanese': 'jpn',
                  'Javanese': 'jav',
                  'Kalaallisut, Greenlandic': 'kal',
                  'Kannada': 'kan',
                  'Kanuri': 'kau',
                  'Kashmiri': 'kas',
                  'Kazakh': 'kaz',
                  'Khmer': 'khm',
                  'Kikuyu, Gikuyu': 'kik',
                  'Kinyarwanda': 'kin',
                  'Kirundi': 'run',
                  'Komi': 'kom',
                  'Kongo': 'kon',
                  'Korean': 'kor',
                  'Kurdish': 'kur',
                  'Kwanyama, Kuanyama': 'kua',
                  'Kyrgyz': 'kir',
                  'Lao': 'lao',
                  'Latin': 'lat',
                  'Latvian': 'lav',
                  'Limburgish, Limburgan, Limburger': 'lim',
                  'Lingala': 'lin',
                  'Lithuanian': 'lit',
                  'Luba-Katanga': 'lub',
                  'Luxembourgish, Letzeburgesch': 'ltz',
                  'Macedonian': 'mkd',
                  'Malagasy': 'mlg',
                  'Malay': 'msa',
                  'Malayalam': 'mal',
                  'Maltese': 'mlt',
                  'Manx': 'glv',
                  'Marathi (Marāṭhī)': 'mar',
                  'Marshallese': 'mah',
                  'Mongolian': 'mon',
                  'Māori': 'mri',
                  'Nauru': 'nau',
                  'Navajo, Navaho': 'nav',
                  'Ndonga': 'ndo',
                  'Nepali': 'nep',
                  'North Ndebele': 'nde',
                  'Northern Sami': 'sme',
                  'Norwegian': 'nor',
                  'Norwegian Bokmål': 'nob',
                  'Norwegian Nynorsk': 'nno',
                  'Nuosu': 'iii',
                  'Occitan': 'oci',
                  'Ojibwe, Ojibwa': 'oji',
                  'Old Church Slavonic, Church Slavonic, Old Bulgarian': 'chu',
                  'Oriya': 'ori',
                  'Oromo': 'orm',
                  'Ossetian, Ossetic': 'oss',
                  'Panjabi, Punjabi': 'pan',
                  'Pashto, Pushto': 'pus',
                  'Persian (Farsi)': 'fas',
                  'Polish': 'pol',
                  'Portuguese': 'por',
                  'Pāli': 'pli',
                  'Quechua': 'que',
                  'Romanian': 'ron',
                  'Romansh': 'roh',
                  'Russian': 'rus',
                  'Samoan': 'smo',
                  'Sango': 'sag',
                  'Sanskrit (Saṁskṛta)': 'san',
                  'Sardinian': 'srd',
                  'Scottish Gaelic; Gaelic': 'gla',
                  'Serbian': 'srp',
                  'Shona': 'sna',
                  'Sindhi': 'snd',
                  'Sinhala, Sinhalese': 'sin',
                  'Slovak': 'slk',
                  'Slovene': 'slv',
                  'Somali': 'som',
                  'South Azerbaijani': 'azb',
                  'South Ndebele': 'nbl',
                  'Southern Sotho': 'sot',
                  'Spanish; Castilian': 'spa',
                  'Sundanese': 'sun',
                  'Swahili': 'swa',
                  'Swati': 'ssw',
                  'Swedish': 'swe',
                  'Tagalog': 'tgl',
                  'Tahitian': 'tah',
                  'Tajik': 'tgk',
                  'Tamil': 'tam',
                  'Tatar': 'tat',
                  'Telugu': 'tel',
                  'Thai': 'tha',
                  'Tibetan Standard, Tibetan, Central': 'bod',
                  'Tigrinya': 'tir',
                  'Tonga (Tonga Islands)': 'ton',
                  'Tsonga': 'tso',
                  'Tswana': 'tsn',
                  'Turkish': 'tur',
                  'Turkmen': 'tuk',
                  'Twi': 'twi',
                  'Ukrainian': 'ukr',
                  'Urdu': 'urd',
                  'Uyghur, Uighur': 'uig',
                  'Uzbek': 'uzb',
                  'Venda': 'ven',
                  'Vietnamese': 'vie',
                  'Volapük': 'vol',
                  'Walloon': 'wln',
                  'Welsh': 'cym',
                  'Western Frisian': 'fry',
                  'Wolof': 'wol',
                  'Xhosa': 'xho',
                  'Yiddish': 'yid',
                  'Yoruba': 'yor',
                  'Zhuang, Chuang': 'zha',
                  'Zulu': 'zul'}

str2iso_639_2B = {'Abkhaz': 'abk',
                  'Afar': 'aar',
                  'Afrikaans': 'afr',
                  'Akan': 'aka',
                  'Albanian': 'alb',
                  'Amharic': 'amh',
                  'Arabic': 'ara',
                  'Aragonese': 'arg',
                  'Armenian': 'arm',
                  'Assamese': 'asm',
                  'Avaric': 'ava',
                  'Avestan': 'ave',
                  'Aymara': 'aym',
                  'Azerbaijani': 'aze',
                  'Bambara': 'bam',
                  'Bashkir': 'bak',
                  'Basque': 'baq',
                  'Belarusian': 'bel',
                  'Bengali; Bangla': 'ben',
                  'Bihari': 'bih',
                  'Bislama': 'bis',
                  'Bosnian': 'bos',
                  'Breton': 'bre',
                  'Bulgarian': 'bul',
                  'Burmese': 'bur',
                  'Catalan; Valencian': 'cat',
                  'Chamorro': 'cha',
                  'Chechen': 'che',
                  'Chichewa; Chewa; Nyanja': 'nya',
                  'Chinese': 'chi',
                  'Chuvash': 'chv',
                  'Cornish': 'cor',
                  'Corsican': 'cos',
                  'Cree': 'cre',
                  'Croatian': 'hrv',
                  'Czech': 'cze',
                  'Danish': 'dan',
                  'Divehi; Dhivehi; Maldivian;': 'div',
                  'Dutch': 'dut',
                  'Dzongkha': 'dzo',
                  'English': 'eng',
                  'Esperanto': 'epo',
                  'Estonian': 'est',
                  'Ewe': 'ewe',
                  'Faroese': 'fao',
                  'Fijian': 'fij',
                  'Finnish': 'fin',
                  'French': 'fre',
                  'Fula; Fulah; Pulaar; Pular': 'ful',
                  'Galician': 'glg',
                  'Ganda': 'lug',
                  'Georgian': 'geo',
                  'German': 'ger',
                  'Greek, Modern': 'gre',
                  'Guaraní': 'grn',
                  'Gujarati': 'guj',
                  'Haitian; Haitian Creole': 'hat',
                  'Hausa': 'hau',
                  'Hebrew (modern)': 'heb',
                  'Herero': 'her',
                  'Hindi': 'hin',
                  'Hiri Motu': 'hmo',
                  'Hungarian': 'hun',
                  'Icelandic': 'ice',
                  'Ido': 'ido',
                  'Igbo': 'ibo',
                  'Indonesian': 'ind',
                  'Interlingua': 'ina',
                  'Interlingue': 'ile',
                  'Inuktitut': 'iku',
                  'Inupiaq': 'ipk',
                  'Irish': 'gle',
                  'Italian': 'ita',
                  'Japanese': 'jpn',
                  'Javanese': 'jav',
                  'Kalaallisut, Greenlandic': 'kal',
                  'Kannada': 'kan',
                  'Kanuri': 'kau',
                  'Kashmiri': 'kas',
                  'Kazakh': 'kaz',
                  'Khmer': 'khm',
                  'Kikuyu, Gikuyu': 'kik',
                  'Kinyarwanda': 'kin',
                  'Kirundi': 'run',
                  'Komi': 'kom',
                  'Kongo': 'kon',
                  'Korean': 'kor',
                  'Kurdish': 'kur',
                  'Kwanyama, Kuanyama': 'kua',
                  'Kyrgyz': 'kir',
                  'Lao': 'lao',
                  'Latin': 'lat',
                  'Latvian': 'lav',
                  'Limburgish, Limburgan, Limburger': 'lim',
                  'Lingala': 'lin',
                  'Lithuanian': 'lit',
                  'Luba-Katanga': 'lub',
                  'Luxembourgish, Letzeburgesch': 'ltz',
                  'Macedonian': 'mac',
                  'Malagasy': 'mlg',
                  'Malay': 'may',
                  'Malayalam': 'mal',
                  'Maltese': 'mlt',
                  'Manx': 'glv',
                  'Marathi (Marāṭhī)': 'mar',
                  'Marshallese': 'mah',
                  'Mongolian': 'mon',
                  'Māori': 'mao',
                  'Nauru': 'nau',
                  'Navajo, Navaho': 'nav',
                  'Ndonga': 'ndo',
                  'Nepali': 'nep',
                  'North Ndebele': 'nde',
                  'Northern Sami': 'sme',
                  'Norwegian': 'nor',
                  'Norwegian Bokmål': 'nob',
                  'Norwegian Nynorsk': 'nno',
                  'Nuosu': 'iii',
                  'Occitan': 'oci',
                  'Ojibwe, Ojibwa': 'oji',
                  'Old Church Slavonic, Church Slavonic, Old Bulgarian': 'chu',
                  'Oriya': 'ori',
                  'Oromo': 'orm',
                  'Ossetian, Ossetic': 'oss',
                  'Panjabi, Punjabi': 'pan',
                  'Pashto, Pushto': 'pus',
                  'Persian (Farsi)': 'per',
                  'Polish': 'pol',
                  'Portuguese': 'por',
                  'Pāli': 'pli',
                  'Quechua': 'que',
                  'Romanian': 'rum',
                  'Romansh': 'roh',
                  'Russian': 'rus',
                  'Samoan': 'smo',
                  'Sango': 'sag',
                  'Sanskrit (Saṁskṛta)': 'san',
                  'Sardinian': 'srd',
                  'Scottish Gaelic; Gaelic': 'gla',
                  'Serbian': 'srp',
                  'Shona': 'sna',
                  'Sindhi': 'snd',
                  'Sinhala, Sinhalese': 'sin',
                  'Slovak': 'slo',
                  'Slovene': 'slv',
                  'Somali': 'som',
                  'South Azerbaijani': 'azb',
                  'South Ndebele': 'nbl',
                  'Southern Sotho': 'sot',
                  'Spanish; Castilian': 'spa',
                  'Sundanese': 'sun',
                  'Swahili': 'swa',
                  'Swati': 'ssw',
                  'Swedish': 'swe',
                  'Tagalog': 'tgl',
                  'Tahitian': 'tah',
                  'Tajik': 'tgk',
                  'Tamil': 'tam',
                  'Tatar': 'tat',
                  'Telugu': 'tel',
                  'Thai': 'tha',
                  'Tibetan Standard, Tibetan, Central': 'tib',
                  'Tigrinya': 'tir',
                  'Tonga (Tonga Islands)': 'ton',
                  'Tsonga': 'tso',
                  'Tswana': 'tsn',
                  'Turkish': 'tur',
                  'Turkmen': 'tuk',
                  'Twi': 'twi',
                  'Ukrainian': 'ukr',
                  'Urdu': 'urd',
                  'Uyghur, Uighur': 'uig',
                  'Uzbek': 'uzb',
                  'Venda': 'ven',
                  'Vietnamese': 'vie',
                  'Volapük': 'vol',
                  'Walloon': 'wln',
                  'Welsh': 'wel',
                  'Western Frisian': 'fry',
                  'Wolof': 'wol',
                  'Xhosa': 'xho',
                  'Yiddish': 'yid',
                  'Yoruba': 'yor',
                  'Zhuang, Chuang': 'zha',
                  'Zulu': 'zul'}

str2iso_639_3 = {'Abkhaz': 'abk',
                 'Afar': 'aar',
                 'Afrikaans': 'afr',
                 'Akan': 'aka + 2',
                 'Albanian': 'sqi + 4',
                 'Amharic': 'amh',
                 'Arabic': 'ara + 30',
                 'Aragonese': 'arg',
                 'Armenian': 'hye',
                 'Assamese': 'asm',
                 'Avaric': 'ava',
                 'Avestan': 'ave',
                 'Aymara': 'aym + 2',
                 'Azerbaijani': 'aze + 2',
                 'Bambara': 'bam',
                 'Bashkir': 'bak',
                 'Basque': 'eus',
                 'Belarusian': 'bel',
                 'Bengali; Bangla': 'ben',
                 'Bihari': '–',
                 'Bislama': 'bis',
                 'Bosnian': 'bos',
                 'Breton': 'bre',
                 'Bulgarian': 'bul',
                 'Burmese': 'mya',
                 'Catalan; Valencian': 'cat',
                 'Chamorro': 'cha',
                 'Chechen': 'che',
                 'Chichewa; Chewa; Nyanja': 'nya',
                 'Chinese': 'zho + 13',
                 'Chuvash': 'chv',
                 'Cornish': 'cor',
                 'Corsican': 'cos',
                 'Cree': 'cre + 6',
                 'Croatian': 'hrv',
                 'Czech': 'ces',
                 'Danish': 'dan',
                 'Divehi; Dhivehi; Maldivian;': 'div',
                 'Dutch': 'nld',
                 'Dzongkha': 'dzo',
                 'English': 'eng',
                 'Esperanto': 'epo',
                 'Estonian': 'est + 2',
                 'Ewe': 'ewe',
                 'Faroese': 'fao',
                 'Fijian': 'fij',
                 'Finnish': 'fin',
                 'French': 'fra',
                 'Fula; Fulah; Pulaar; Pular': 'ful + 9',
                 'Galician': 'glg',
                 'Ganda': 'lug',
                 'Georgian': 'kat',
                 'German': 'deu',
                 'Greek, Modern': 'ell',
                 'Guaraní': 'grn + 5',
                 'Gujarati': 'guj',
                 'Haitian; Haitian Creole': 'hat',
                 'Hausa': 'hau',
                 'Hebrew (modern)': 'heb',
                 'Herero': 'her',
                 'Hindi': 'hin',
                 'Hiri Motu': 'hmo',
                 'Hungarian': 'hun',
                 'Icelandic': 'isl',
                 'Ido': 'ido',
                 'Igbo': 'ibo',
                 'Indonesian': 'ind',
                 'Interlingua': 'ina',
                 'Interlingue': 'ile',
                 'Inuktitut': 'iku + 2',
                 'Inupiaq': 'ipk + 2',
                 'Irish': 'gle',
                 'Italian': 'ita',
                 'Japanese': 'jpn',
                 'Javanese': 'jav',
                 'Kalaallisut, Greenlandic': 'kal',
                 'Kannada': 'kan',
                 'Kanuri': 'kau + 3',
                 'Kashmiri': 'kas',
                 'Kazakh': 'kaz',
                 'Khmer': 'khm',
                 'Kikuyu, Gikuyu': 'kik',
                 'Kinyarwanda': 'kin',
                 'Kirundi': 'run',
                 'Komi': 'kom + 2',
                 'Kongo': 'kon + 3',
                 'Korean': 'kor',
                 'Kurdish': 'kur + 3',
                 'Kwanyama, Kuanyama': 'kua',
                 'Kyrgyz': 'kir',
                 'Lao': 'lao',
                 'Latin': 'lat',
                 'Latvian': 'lav + 2',
                 'Limburgish, Limburgan, Limburger': 'lim',
                 'Lingala': 'lin',
                 'Lithuanian': 'lit',
                 'Luba-Katanga': 'lub',
                 'Luxembourgish, Letzeburgesch': 'ltz',
                 'Macedonian': 'mkd',
                 'Malagasy': 'mlg + 10',
                 'Malay': 'msa + 13',
                 'Malayalam': 'mal',
                 'Maltese': 'mlt',
                 'Manx': 'glv',
                 'Marathi (Marāṭhī)': 'mar',
                 'Marshallese': 'mah',
                 'Mongolian': 'mon + 2',
                 'Māori': 'mri',
                 'Nauru': 'nau',
                 'Navajo, Navaho': 'nav',
                 'Ndonga': 'ndo',
                 'Nepali': 'nep',
                 'North Ndebele': 'nde',
                 'Northern Sami': 'sme',
                 'Norwegian': 'nor + 2',
                 'Norwegian Bokmål': 'nob',
                 'Norwegian Nynorsk': 'nno',
                 'Nuosu': 'iii',
                 'Occitan': 'oci',
                 'Ojibwe, Ojibwa': 'oji + 7',
                 'Old Church Slavonic, Church Slavonic, Old Bulgarian': 'chu',
                 'Oriya': 'ori',
                 'Oromo': 'orm + 4',
                 'Ossetian, Ossetic': 'oss',
                 'Panjabi, Punjabi': 'pan',
                 'Pashto, Pushto': 'pus + 3',
                 'Persian (Farsi)': 'fas + 2',
                 'Polish': 'pol',
                 'Portuguese': 'por',
                 'Pāli': 'pli',
                 'Quechua': 'que + 44',
                 'Romanian': 'ron',
                 'Romansh': 'roh',
                 'Russian': 'rus',
                 'Samoan': 'smo',
                 'Sango': 'sag',
                 'Sanskrit (Saṁskṛta)': 'san',
                 'Sardinian': 'srd + 4',
                 'Scottish Gaelic; Gaelic': 'gla',
                 'Serbian': 'srp',
                 'Shona': 'sna',
                 'Sindhi': 'snd',
                 'Sinhala, Sinhalese': 'sin',
                 'Slovak': 'slk',
                 'Slovene': 'slv',
                 'Somali': 'som',
                 'South Azerbaijani': 'azb',
                 'South Ndebele': 'nbl',
                 'Southern Sotho': 'sot',
                 'Spanish; Castilian': 'spa',
                 'Sundanese': 'sun',
                 'Swahili': 'swa + 2',
                 'Swati': 'ssw',
                 'Swedish': 'swe',
                 'Tagalog': 'tgl',
                 'Tahitian': 'tah',
                 'Tajik': 'tgk',
                 'Tamil': 'tam',
                 'Tatar': 'tat',
                 'Telugu': 'tel',
                 'Thai': 'tha',
                 'Tibetan Standard, Tibetan, Central': 'bod',
                 'Tigrinya': 'tir',
                 'Tonga (Tonga Islands)': 'ton',
                 'Tsonga': 'tso',
                 'Tswana': 'tsn',
                 'Turkish': 'tur',
                 'Turkmen': 'tuk',
                 'Twi': 'twi',
                 'Ukrainian': 'ukr',
                 'Urdu': 'urd',
                 'Uyghur, Uighur': 'uig',
                 'Uzbek': 'uzb + 2',
                 'Venda': 'ven',
                 'Vietnamese': 'vie',
                 'Volapük': 'vol',
                 'Walloon': 'wln',
                 'Welsh': 'cym',
                 'Western Frisian': 'fry',
                 'Wolof': 'wol',
                 'Xhosa': 'xho',
                 'Yiddish': 'yid + 2',
                 'Yoruba': 'yor',
                 'Zhuang, Chuang': 'zha + 16',
                 'Zulu': 'zul'}


def convert(isoType, langName):
	if isoType == 1:
		return str2iso_639_1[langName]
	elif isoType == '2T':
		return str2iso_639_2T[langName]
	elif isoType == '2B':
		return str2iso_639_2B[langName]
	elif isoType == 3:
		return str2iso_639_3[langName]
